# Test values for atmosphere (local test only)

# List of dbs that need to be created
databases:
- name: my_app

# List of users with their accesses
users:
- username: alice
  passwordSecretName: my-secret
  passwordSecretKey: alice-db-password
  accesses:
  - db: my-app
    readOnly: true
- username: bob
  passwordSecretName: my-secret
  passwordSecretKey: bob-db-password
  accesses:
  - db: my-app
    readOnly: true
    schemas:
    - pub
- username: cloe
  passwordSecretName: my-secret
  passwordSecretKey: cloe-db-password
  accesses:
  - db: my-app

# Way to connect to the database
postgresqlAdminCredentials:
  initDb: init_db
  secretName: my-secret
  secretKeys:
    host: PGHOST
    password: PGPASSWORD
    user: PGUSER
    port: PGPORT
