# Default values for postgres-db-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/bitnami/postgresql
  pullPolicy: IfNotPresent
  tag: 11.7.0-debian-10-r43

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# List of dbs that need to be created
databases: []
# - name: db_1
# - name: db_2

# List of users with their accesses
users: []
# - username: alice
#   passwordSecretName: my-secret
#   passwordSecretKey: alice-db-password
#   accesses:
#   - db: db_1
#     readOnly: true (false by default)
#     schemas: (used only if readOnly is true, additional schemas the user will have access to. It will always include `public` even if omitted from this list and/or the list is not present/empty)
#     - pub
#     targetUser: bob (empty by default, used only if readOnly is true, equivalent to the admin user selected in the postgresAdminCredentials. Will give accesses to all the future tables this user will create in the set schemas.)
#   - db: db_2

postgresqlAdminCredentials:
  initDb: ""
  secretName: ""
  secretKeys:
    host: PGHOST
    password: PGPASSWORD
    user: PGUSER
    port: PGPORT
