# Test values for atmosphere (local test only)

# List of buckets to create
buckets:
  bucket1: {}
  bucket2:
    purge: true
  bucket3:
    policy: upload
  bucket4:
    versioning: true

# List of users with their accesses
users:
  - userCredentialsSecret: alice-minio-secret
    usernameSecretKey: username1
    passwordSecretKey: password1
    policy: policy-bucket1and2
  - userCredentialsSecret: bob-minio-secret
    usernameSecretKey: username2
    passwordSecretKey: password2
    policy: readonly
  - userCredentialsSecret: carl-minio-secret
    policy: policy-bucket3
  - userCredentialsSecret: dave-minio-secret

policies:
  - name: policy-bucket1and2
    readOnly: true
    buckets:
      - "bucket1"
      - "bucket2"
  - name: policy-bucket3
    readOnly: false
    buckets:
      - "bucket3"


minioAdminCredentials:
  secretName: minio-secrets
  secretKeys:
    accessKey: MINIO_ACCESS_KEY
    secretKey: MINIO_SECRET_KEY
    endpointUrl: AWS_ENDPOINT_URL
    useSsl: USE_SSL
