# Default values for minio-manager.
# This is a YAML-formatted file.

image:
  repository: minio/mc
  pullPolicy: IfNotPresent
  tag: RELEASE.2020-04-04T05-28-55Z

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# List of buckets to create
buckets: {}
#  bucket1: # name of the bucket to create
#     policy: ""  # Set a policy for anonymous users on this bucket. Allowed policies are: [none, download, upload, public] (https://docs.min.io/docs/minio-client-complete-guide.html#policy)
#     purge: false  # purge the bucket if already exists if set to true
#  bucket2
#     policy: ""
#     purge: ""

# List of users with their accesses
users: []
# - userCredentialsSecret: my-secret
#   usernameSecretKey: username
#   passwordSecretKey: password
#   policy: readwrite

policies: []
# - name: new-policy
#   readOnly: true (default to true)
#   buckets: []

minioAdminCredentials:
  secretName: ""
  secretKeys:
    accessKey: MINIO_ACCESS_KEY
    secretKey: MINIO_SECRET_KEY
    endpointUrl: MINIO_ENDPOINT_URL
    useSsl: MINIO_USE_SSL
