# Default values for minio-manager.
# This is a YAML-formatted file.

image:
  repository: minio/mc
  pullPolicy: IfNotPresent
  tag: RELEASE.2020-11-25T23-04-07Z

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# List of buckets to create
buckets: {}
#  bucket1: # name of the bucket to create
#     policy: ""  # Set a policy for anonymous users on this bucket. Allowed policies are: [none, download, upload, public] (https://docs.min.io/docs/minio-client-complete-guide.html#policy)
#     purge: false  # purge the bucket if already exists if set to true
#     versioning: ""  # versioning of the bucket. Only available in erasure coded and distributed erasure coded setups (https://docs.min.io/docs/minio-bucket-versioning-guide.html)
#  bucket2:
#     policy: ""
#     purge: ""

# List of users with their accesses
users: []
# - userCredentialsSecret: my-secret
#   accessKey: accesskey
#   secretKey: secretkey
#   policy: readwrite

policies: []
# - name: new-policy
#   buckets:
#   - name: bucket1
#     actions:
#       - "s3:ListBucket"
#       - "s3:GetObject"
#   - name: bucket2
#     actions:
#       - "s3:ListBucket"
#       - "s3:GetObject"
#       - "s3:PutObject"
#       - "s3:DeleteObject"

minioAdminCredentials:
  secretName: ""
  secretKeys:
    accessKey: accesskey
    secretKey: secretkey
    endpointUrl: endpointUrl
    useSsl: useSsl
