apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgdbsync.fullname" . }}-configmap
data:
  temp_table_sync.sh: |-
{{ .Files.Get "temp_table_sync.sh" | indent 4 }}
  timestamp_sync.sh: |-
{{ .Files.Get "timestamp_sync.sh" | indent 4 }}
