{{- if not .Values.customExportStatementConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgdbsync.fullname" . }}-export-statement
data:
  export.sql: |-
    CREATE TEMP VIEW _TIMESTAMP_EXP AS
    SELECT
    *
    FROM :schema.:"table"
    WHERE :"column" > :'oldest_record'::timestamptz
    AND :"column" < now()::timestamp - interval :'lag_minutes' minute;
    \copy (select * from _TIMESTAMP_EXP) TO '/tmp/pg-to-pg-sync.copy' WITH CSV;
  export_all.sql: |-
    \copy (select * from :schema.:"table") TO '/tmp/pg-to-pg-sync.copy' WITH CSV;
  create_table.sql: |-
    CREATE TABLE IF NOT EXISTS :schema.:"table" :list_column_names_data_types;
{{- end }}
