name: Lint Charts

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (lint)
        run: |
          ct lint --all --debug --config $CONFIG
        env:
          CONFIG: .github/ct.yaml

      - name: Kubeval the chart
        uses: desaintmartin/helm-kubeval-action@v1.0.2
        with:
          path: ./charts
          version: 1.15.7
